version: '3'
services:
  db:
    image: postgres
    container_name: postgresql
    environment:
      # POSTGRES_PASSWORD: '123456'
      LANG: C.UTF-8
    volumes:
      - postgre-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgre-data:
